"""portals: approvals, pan, shared coupons, settlement adjustments

Revision ID: 044334a9ff70
Revises: f2c09c38a12f
Create Date: 2026-09-12 08:13:35.372648+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '044334a9ff70'
down_revision: str | None = 'f2c09c38a12f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('requested_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_provider_id', sa.UUID(), nullable=True),
    sa.Column('decided_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=300), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_admin_id'], ['admin_users.id'], name=op.f('fk_approval_requests_decided_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_admin_id'], ['admin_users.id'], name=op.f('fk_approval_requests_requested_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_provider_id'], ['providers.id'], name=op.f('fk_approval_requests_requested_by_provider_id_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_action'), 'approval_requests', ['action'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.add_column('coupons', sa.Column('provider_share_pct', sa.Integer(), server_default='0', nullable=False))
    op.add_column('providers', sa.Column('pan_enc', sa.String(length=512), nullable=True))
    op.add_column('providers', sa.Column('entity_type', sa.String(length=20), nullable=True))
    op.add_column('providers', sa.Column('payouts_on_hold', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('settlements', sa.Column('adjustments_paise', sa.Integer(), nullable=False))
    op.add_column('settlements', sa.Column('generated_by_admin_id', sa.UUID(), nullable=True))
    op.add_column('settlements', sa.Column('payout_method', sa.String(length=16), nullable=True))
    op.create_foreign_key(op.f('fk_settlements_generated_by_admin_id_admin_users'), 'settlements', 'admin_users', ['generated_by_admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_settlements_generated_by_admin_id_admin_users'), 'settlements', type_='foreignkey')
    op.drop_column('settlements', 'payout_method')
    op.drop_column('settlements', 'generated_by_admin_id')
    op.drop_column('settlements', 'adjustments_paise')
    op.drop_column('providers', 'payouts_on_hold')
    op.drop_column('providers', 'entity_type')
    op.drop_column('providers', 'pan_enc')
    op.drop_column('coupons', 'provider_share_pct')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_action'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
