"""initial schema

Revision ID: 08f1526aeabc
Revises: 
Create Date: 2026-09-11 20:18:55.064310+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '08f1526aeabc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turfs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.String(length=500)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('rating_avg', sa.Float(), server_default='4.5', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turfs'))
    )
    op.create_index(op.f('ix_turfs_area'), 'turfs', ['area'], unique=False)
    op.create_index(op.f('ix_turfs_slug'), 'turfs', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('dominant_foot', sa.String(length=8), nullable=True),
    sa.Column('self_skill_level', sa.String(length=16), nullable=True),
    sa.Column('preferred_sports', postgresql.ARRAY(sa.String(length=16)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lng', sa.Float(), nullable=True),
    sa.Column('home_area', sa.String(length=80), nullable=True),
    sa.Column('wallet_balance_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('onboarded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_bot', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=12), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_table('bench_statuses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), server_default='5', nullable=False),
    sa.Column('sports', postgresql.ARRAY(sa.String(length=16)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bench_statuses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_bench_statuses'))
    )
    op.create_index(op.f('ix_bench_statuses_is_active'), 'bench_statuses', ['is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=300), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('pitches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turf_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_indoor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_camera', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('camera_price_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price_per_hour_paise', sa.Integer(), nullable=False),
    sa.Column('peak_price_per_hour_paise', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turf_id'], ['turfs.id'], name=op.f('fk_pitches_turf_id_turfs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pitches'))
    )
    op.create_index(op.f('ix_pitches_sport'), 'pitches', ['sport'], unique=False)
    op.create_index(op.f('ix_pitches_turf_id'), 'pitches', ['turf_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('streak_weeks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_match_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matches_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matches_hosted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('subs_made', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dropouts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('no_shows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ratings_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ratings_given', sa.Integer(), server_default='0', nullable=False),
    sa.Column('distinct_raters', sa.Integer(), server_default='0', nullable=False),
    sa.Column('weight_sum', sa.Float(), server_default='0', nullable=False),
    sa.Column('skill_wsum', sa.Float(), server_default='0', nullable=False),
    sa.Column('fair_play_wsum', sa.Float(), server_default='0', nullable=False),
    sa.Column('reliability_wsum', sa.Float(), server_default='0', nullable=False),
    sa.Column('avg_skill', sa.Float(), nullable=True),
    sa.Column('avg_fair_play', sa.Float(), nullable=True),
    sa.Column('avg_reliability', sa.Float(), nullable=True),
    sa.Column('true_skill', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=16), server_default='rookie', nullable=False),
    sa.Column('is_verified_playmaker', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tag_counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_player_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_player_stats'))
    )
    op.create_index(op.f('ix_player_stats_true_skill'), 'player_stats', ['true_skill'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_code', sa.String(length=32), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_badges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'badge_code', name=op.f('pk_user_badges'))
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('balance_after_paise', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallet_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_transactions'))
    )
    op.create_index('ix_wallet_txn_user_created', 'wallet_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('xp_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_events'))
    )
    op.create_index('ix_xp_events_user_created', 'xp_events', ['user_id', 'created_at'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('is_peak', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='available', nullable=False),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('held_by_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_slots_booking_id_bookings'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['held_by_id'], ['users.id'], name=op.f('fk_slots_held_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('fk_slots_pitch_id_pitches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots')),
    sa.UniqueConstraint('pitch_id', 'start_at', name='uq_slots_pitch_start')
    )
    op.create_index(op.f('ix_slots_pitch_id'), 'slots', ['pitch_id'], unique=False)
    op.create_index('ix_slots_status_start', 'slots', ['status', 'start_at'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pitch_fee_paise', sa.Integer(), nullable=False),
    sa.Column('recording_fee_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('recorded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transferred_from_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('fk_bookings_host_id_users')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_bookings_slot_id_slots')),
    sa.ForeignKeyConstraint(['transferred_from_id'], ['bookings.id'], name=op.f('fk_bookings_transferred_from_id_bookings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_code'), 'bookings', ['code'], unique=True)
    op.create_index(op.f('ix_bookings_host_id'), 'bookings', ['host_id'], unique=False)
    op.create_index(op.f('ix_bookings_slot_id'), 'bookings', ['slot_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('lobbies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('turf_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('visibility', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('total_spots', sa.Integer(), nullable=False),
    sa.Column('share_paise', sa.Integer(), nullable=False),
    sa.Column('pay_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_true_skill', sa.Float(), nullable=True),
    sa.Column('verified_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recorded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_lobbies_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('fk_lobbies_host_id_users')),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('fk_lobbies_pitch_id_pitches')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_lobbies_slot_id_slots')),
    sa.ForeignKeyConstraint(['turf_id'], ['turfs.id'], name=op.f('fk_lobbies_turf_id_turfs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lobbies')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_lobbies_booking_id'))
    )
    op.create_index(op.f('ix_lobbies_code'), 'lobbies', ['code'], unique=True)
    op.create_index(op.f('ix_lobbies_host_id'), 'lobbies', ['host_id'], unique=False)
    op.create_index(op.f('ix_lobbies_pitch_id'), 'lobbies', ['pitch_id'], unique=False)
    op.create_index(op.f('ix_lobbies_slot_id'), 'lobbies', ['slot_id'], unique=False)
    op.create_index(op.f('ix_lobbies_sport'), 'lobbies', ['sport'], unique=False)
    op.create_index(op.f('ix_lobbies_start_at'), 'lobbies', ['start_at'], unique=False)
    op.create_index(op.f('ix_lobbies_turf_id'), 'lobbies', ['turf_id'], unique=False)
    op.create_index('ix_lobbies_visibility_status_start', 'lobbies', ['visibility', 'status', 'start_at'], unique=False)
    op.create_table('lobby_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('team', sa.String(length=1), nullable=True),
    sa.Column('share_paise', sa.Integer(), nullable=False),
    sa.Column('paid_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('compensated_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sos_id', sa.UUID(), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_lobby_members_lobby_id_lobbies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sos_id'], ['sos_requests.id'], name=op.f('fk_lobby_members_sos_id_sos_requests'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lobby_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lobby_members')),
    sa.UniqueConstraint('lobby_id', 'user_id', name='uq_lobby_members_lobby_user')
    )
    op.create_index(op.f('ix_lobby_members_lobby_id'), 'lobby_members', ['lobby_id'], unique=False)
    op.create_index(op.f('ix_lobby_members_user_id'), 'lobby_members', ['user_id'], unique=False)
    op.create_table('lobby_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_lobby_messages_lobby_id_lobbies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lobby_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lobby_messages'))
    )
    op.create_index('ix_lobby_messages_lobby_created', 'lobby_messages', ['lobby_id', 'created_at'], unique=False)
    op.create_table('match_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('ratee_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.SmallInteger(), nullable=False),
    sa.Column('fair_play', sa.SmallInteger(), nullable=False),
    sa.Column('reliability', sa.SmallInteger(), nullable=False),
    sa.Column('showed_up', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('true_skill_after', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_match_ratings_lobby_id_lobbies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ratee_id'], ['users.id'], name=op.f('fk_match_ratings_ratee_id_users')),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name=op.f('fk_match_ratings_rater_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_ratings')),
    sa.UniqueConstraint('lobby_id', 'rater_id', 'ratee_id', name='uq_match_ratings_triplet')
    )
    op.create_index(op.f('ix_match_ratings_lobby_id'), 'match_ratings', ['lobby_id'], unique=False)
    op.create_index(op.f('ix_match_ratings_ratee_id'), 'match_ratings', ['ratee_id'], unique=False)
    op.create_index(op.f('ix_match_ratings_rater_id'), 'match_ratings', ['rater_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('process_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_recordings_lobby_id_lobbies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('fk_recordings_pitch_id_pitches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings')),
    sa.UniqueConstraint('lobby_id', name=op.f('uq_recordings_lobby_id'))
    )
    op.create_index(op.f('ix_recordings_status'), 'recordings', ['status'], unique=False)
    op.create_table('sos_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=8), nullable=False),
    sa.Column('spots_needed', sa.Integer(), nullable=False),
    sa.Column('spots_filled', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('original_share_paise', sa.Integer(), nullable=False),
    sa.Column('discounted_share_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sos_requests_created_by_id_users')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_sos_requests_lobby_id_lobbies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sos_requests'))
    )
    op.create_index(op.f('ix_sos_requests_lobby_id'), 'sos_requests', ['lobby_id'], unique=False)
    op.create_index(op.f('ix_sos_requests_status'), 'sos_requests', ['status'], unique=False)
    op.create_table('weather_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('precipitation_probability', sa.Integer(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_weather_alerts_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_weather_alerts_lobby_id_lobbies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_alerts'))
    )
    op.create_index(op.f('ix_weather_alerts_lobby_id'), 'weather_alerts', ['lobby_id'], unique=False)
    op.create_index(op.f('ix_weather_alerts_status'), 'weather_alerts', ['status'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=30)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_clips_recording_id_recordings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clips_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clips'))
    )
    op.create_index(op.f('ix_clips_recording_id'), 'clips', ['recording_id'], unique=False)
    op.create_index(op.f('ix_clips_user_id'), 'clips', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=12), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('credits_applied_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payable_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('provider_order_id', sa.String(length=64), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_payments_lobby_id_lobbies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['lobby_members.id'], name=op.f('fk_payments_member_id_lobby_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider_order_id', name=op.f('uq_payments_provider_order_id')),
    sa.UniqueConstraint('provider_payment_id', name=op.f('uq_payments_provider_payment_id'))
    )
    op.create_index(op.f('ix_payments_lobby_id'), 'payments', ['lobby_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('sos_dispatches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sos_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response', sa.String(length=10), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sos_id'], ['sos_requests.id'], name=op.f('fk_sos_dispatches_sos_id_sos_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sos_dispatches_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sos_dispatches')),
    sa.UniqueConstraint('sos_id', 'user_id', name='uq_sos_dispatches_sos_user')
    )
    op.create_index(op.f('ix_sos_dispatches_sos_id'), 'sos_dispatches', ['sos_id'], unique=False)
    op.create_index(op.f('ix_sos_dispatches_user_id'), 'sos_dispatches', ['user_id'], unique=False)
    op.create_table('clip_likes',
    sa.Column('clip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('fk_clip_likes_clip_id_clips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clip_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clip_id', 'user_id', name=op.f('pk_clip_likes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clip_likes')
    op.drop_index(op.f('ix_sos_dispatches_user_id'), table_name='sos_dispatches')
    op.drop_index(op.f('ix_sos_dispatches_sos_id'), table_name='sos_dispatches')
    op.drop_table('sos_dispatches')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_lobby_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_clips_user_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_recording_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_weather_alerts_status'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_lobby_id'), table_name='weather_alerts')
    op.drop_table('weather_alerts')
    op.drop_index(op.f('ix_sos_requests_status'), table_name='sos_requests')
    op.drop_index(op.f('ix_sos_requests_lobby_id'), table_name='sos_requests')
    op.drop_table('sos_requests')
    op.drop_index(op.f('ix_recordings_status'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_match_ratings_rater_id'), table_name='match_ratings')
    op.drop_index(op.f('ix_match_ratings_ratee_id'), table_name='match_ratings')
    op.drop_index(op.f('ix_match_ratings_lobby_id'), table_name='match_ratings')
    op.drop_table('match_ratings')
    op.drop_index('ix_lobby_messages_lobby_created', table_name='lobby_messages')
    op.drop_table('lobby_messages')
    op.drop_index(op.f('ix_lobby_members_user_id'), table_name='lobby_members')
    op.drop_index(op.f('ix_lobby_members_lobby_id'), table_name='lobby_members')
    op.drop_table('lobby_members')
    op.drop_index('ix_lobbies_visibility_status_start', table_name='lobbies')
    op.drop_index(op.f('ix_lobbies_turf_id'), table_name='lobbies')
    op.drop_index(op.f('ix_lobbies_start_at'), table_name='lobbies')
    op.drop_index(op.f('ix_lobbies_sport'), table_name='lobbies')
    op.drop_index(op.f('ix_lobbies_slot_id'), table_name='lobbies')
    op.drop_index(op.f('ix_lobbies_pitch_id'), table_name='lobbies')
    op.drop_index(op.f('ix_lobbies_host_id'), table_name='lobbies')
    op.drop_index(op.f('ix_lobbies_code'), table_name='lobbies')
    op.drop_table('lobbies')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_slot_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_host_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_slots_status_start', table_name='slots')
    op.drop_index(op.f('ix_slots_pitch_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index('ix_xp_events_user_created', table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index('ix_wallet_txn_user_created', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_player_stats_true_skill'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_pitches_turf_id'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_sport'), table_name='pitches')
    op.drop_table('pitches')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_bench_statuses_is_active'), table_name='bench_statuses')
    op.drop_table('bench_statuses')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_turfs_slug'), table_name='turfs')
    op.drop_index(op.f('ix_turfs_area'), table_name='turfs')
    op.drop_table('turfs')
    # ### end Alembic commands ###
