"""portals: admin, providers, channels, coupons, settlements

Revision ID: f2c09c38a12f
Revises: 08f1526aeabc
Create Date: 2026-09-12 08:06:57.680515+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.modules.audit.models import AUDIT_APPEND_ONLY_DDL
from sqlalchemy.dialects import postgresql

revision: str = 'f2c09c38a12f'
down_revision: str | None = '08f1526aeabc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('totp_secret_enc', sa.String(length=512), nullable=True),
    sa.Column('totp_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_last_step', sa.Integer(), nullable=True),
    sa.Column('recovery_code_hashes', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('failed_logins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], name=op.f('fk_admin_users_created_by_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_logs_hash'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_type', 'actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=8), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('audience', sa.String(length=8), nullable=False),
    sa.Column('current_refresh_jti', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=60), nullable=True),
    sa.Column('mfa_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    op.create_index('ix_auth_sessions_subject', 'auth_sessions', ['subject_type', 'subject_id'], unique=False)
    op.create_table('sports_catalog',
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('formats', postgresql.ARRAY(sa.String(length=16)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_sports_catalog'))
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admin_users.id'], name=op.f('fk_app_settings_updated_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('segment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='sent', nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], name=op.f('fk_broadcasts_created_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('legal_name', sa.String(length=160), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan_last4', sa.String(length=4), nullable=True),
    sa.Column('contact_name', sa.String(length=80), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=60), server_default='Kochi', nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('status_reason', sa.String(length=300), nullable=True),
    sa.Column('commission_bps', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('settlement_cycle', sa.String(length=10), server_default='weekly', nullable=False),
    sa.Column('bank_account_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account_last4', sa.String(length=4), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=11), nullable=True),
    sa.Column('razorpay_account_id', sa.String(length=40), nullable=True),
    sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admin_users.id'], name=op.f('fk_providers_reviewed_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=True)
    op.create_index(op.f('ix_providers_status'), 'providers', ['status'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('discount_type', sa.String(length=8), nullable=False),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('amount_off_paise', sa.Integer(), nullable=True),
    sa.Column('max_discount_paise', sa.Integer(), nullable=True),
    sa.Column('min_amount_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit_total', sa.Integer(), nullable=True),
    sa.Column('usage_limit_per_user', sa.Integer(), server_default='1', nullable=False),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_booking_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sports', postgresql.ARRAY(sa.String(length=16)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('turf_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('funded_by', sa.String(length=10), server_default='platform', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], name=op.f('fk_coupons_created_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_coupons_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons'))
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('provider_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=30)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_provider_api_keys_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_api_keys_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_provider_api_keys_key_hash'))
    )
    op.create_index(op.f('ix_provider_api_keys_prefix'), 'provider_api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_provider_api_keys_provider_id'), 'provider_api_keys', ['provider_id'], unique=False)
    op.create_table('provider_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('invited_phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('turf_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_members_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provider_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_members')),
    sa.UniqueConstraint('provider_id', 'user_id', name='uq_provider_members_provider_user')
    )
    op.create_index(op.f('ix_provider_members_provider_id'), 'provider_members', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_members_user_id'), 'provider_members', ['user_id'], unique=False)
    op.create_table('provider_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret_enc', sa.String(length=512), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_webhooks_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_webhooks'))
    )
    op.create_index(op.f('ix_provider_webhooks_provider_id'), 'provider_webhooks', ['provider_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('booking_count', sa.Integer(), nullable=False),
    sa.Column('gross_paise', sa.Integer(), nullable=False),
    sa.Column('refunds_paise', sa.Integer(), nullable=False),
    sa.Column('provider_discounts_paise', sa.Integer(), nullable=False),
    sa.Column('commission_bps', sa.Integer(), nullable=False),
    sa.Column('commission_paise', sa.Integer(), nullable=False),
    sa.Column('gst_on_commission_paise', sa.Integer(), nullable=False),
    sa.Column('tcs_paise', sa.Integer(), nullable=False),
    sa.Column('tds_paise', sa.Integer(), nullable=False),
    sa.Column('net_payable_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='draft', nullable=False),
    sa.Column('approved_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_ref', sa.String(length=80), nullable=True),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['admin_users.id'], name=op.f('fk_settlements_approved_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_settlements_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements')),
    sa.UniqueConstraint('provider_id', 'period_start', 'period_end', name='uq_settlements_period')
    )
    op.create_index(op.f('ix_settlements_provider_id'), 'settlements', ['provider_id'], unique=False)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['provider_webhooks.id'], name=op.f('fk_webhook_deliveries_webhook_id_provider_webhooks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_index('ix_webhook_deliveries_due', 'webhook_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('channel_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('url_enc', sa.String(length=2048), nullable=False),
    sa.Column('url_hint', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('last_event_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('etag', sa.String(length=200), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('fk_channel_feeds_pitch_id_pitches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_channel_feeds_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_feeds'))
    )
    op.create_index(op.f('ix_channel_feeds_provider_id'), 'channel_feeds', ['provider_id'], unique=False)
    op.create_table('slot_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('customer_name', sa.String(length=80), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('amount_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payment_mode', sa.String(length=12), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('feed_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['provider_api_keys.id'], name=op.f('fk_slot_blocks_api_key_id_provider_api_keys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_slot_blocks_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feed_id'], ['channel_feeds.id'], name=op.f('fk_slot_blocks_feed_id_channel_feeds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('fk_slot_blocks_pitch_id_pitches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_slot_blocks_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slot_blocks')),
    sa.UniqueConstraint('provider_id', 'source', 'external_ref', name='uq_slot_blocks_external_ref')
    )
    op.create_index('ix_slot_blocks_pitch_start', 'slot_blocks', ['pitch_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_slot_blocks_provider_id'), 'slot_blocks', ['provider_id'], unique=False)
    op.create_table('settlement_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('turf_id', sa.UUID(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_paise', sa.Integer(), nullable=False),
    sa.Column('refunds_paise', sa.Integer(), nullable=False),
    sa.Column('provider_discounts_paise', sa.Integer(), nullable=False),
    sa.Column('commission_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_settlement_lines_booking_id_bookings')),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name=op.f('fk_settlement_lines_settlement_id_settlements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turf_id'], ['turfs.id'], name=op.f('fk_settlement_lines_turf_id_turfs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_lines')),
    sa.UniqueConstraint('booking_id', name='uq_settlement_lines_booking')
    )
    op.create_index(op.f('ix_settlement_lines_settlement_id'), 'settlement_lines', ['settlement_id'], unique=False)
    op.create_table('sync_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('lobby_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=True),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('external_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['channel_feeds.id'], name=op.f('fk_sync_conflicts_feed_id_channel_feeds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_sync_conflicts_lobby_id_lobbies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('fk_sync_conflicts_pitch_id_pitches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_sync_conflicts_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_sync_conflicts_resolved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_sync_conflicts_slot_id_slots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_conflicts'))
    )
    op.create_index(op.f('ix_sync_conflicts_provider_id'), 'sync_conflicts', ['provider_id'], unique=False)
    op.create_index(op.f('ix_sync_conflicts_status'), 'sync_conflicts', ['status'], unique=False)
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=True),
    sa.Column('discount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='applied', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_redemptions_coupon_id_coupons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_coupon_redemptions_lobby_id_lobbies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_coupon_redemptions_payment_id_payments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupon_redemptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_redemptions')),
    sa.UniqueConstraint('payment_id', name='uq_coupon_redemptions_payment')
    )
    op.create_index(op.f('ix_coupon_redemptions_coupon_id'), 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_user_id'), 'coupon_redemptions', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_lobby_members_sos_id_sos_requests'), 'lobby_members', 'sos_requests', ['sos_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('payments', sa.Column('coupon_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('discount_paise', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key(op.f('fk_payments_coupon_id_coupons'), 'payments', 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')
    op.add_column('pitches', sa.Column('ical_export_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_pitches_ical_export_token'), 'pitches', ['ical_export_token'])
    op.add_column('slots', sa.Column('block_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_slots_block_id'), 'slots', ['block_id'], unique=False)
    op.create_foreign_key(op.f('fk_slots_block_id_slot_blocks'), 'slots', 'slot_blocks', ['block_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_slots_booking_id_bookings'), 'slots', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('turfs', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.add_column('turfs', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_turfs_provider_id'), 'turfs', ['provider_id'], unique=False)
    op.create_foreign_key(op.f('fk_turfs_provider_id_providers'), 'turfs', 'providers', ['provider_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('status', sa.String(length=10), server_default='active', nullable=False))
    op.add_column('users', sa.Column('status_reason', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('suspended_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###

    # audit log is append-only at the database level
    for ddl in AUDIT_APPEND_ONLY_DDL:
        op.execute(ddl)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs;")
    op.execute("DROP FUNCTION IF EXISTS audit_logs_block_mutation();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_column('users', 'suspended_until')
    op.drop_column('users', 'status_reason')
    op.drop_column('users', 'status')
    op.drop_constraint(op.f('fk_turfs_provider_id_providers'), 'turfs', type_='foreignkey')
    op.drop_index(op.f('ix_turfs_provider_id'), table_name='turfs')
    op.drop_column('turfs', 'is_featured')
    op.drop_column('turfs', 'provider_id')
    op.drop_constraint(op.f('fk_slots_booking_id_bookings'), 'slots', type_='foreignkey')
    op.drop_constraint(op.f('fk_slots_block_id_slot_blocks'), 'slots', type_='foreignkey')
    op.drop_index(op.f('ix_slots_block_id'), table_name='slots')
    op.drop_column('slots', 'block_id')
    op.drop_constraint(op.f('uq_pitches_ical_export_token'), 'pitches', type_='unique')
    op.drop_column('pitches', 'ical_export_token')
    op.drop_constraint(op.f('fk_payments_coupon_id_coupons'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'discount_paise')
    op.drop_column('payments', 'coupon_id')
    op.drop_constraint(op.f('fk_lobby_members_sos_id_sos_requests'), 'lobby_members', type_='foreignkey')
    op.drop_index(op.f('ix_coupon_redemptions_user_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_id'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_index(op.f('ix_sync_conflicts_status'), table_name='sync_conflicts')
    op.drop_index(op.f('ix_sync_conflicts_provider_id'), table_name='sync_conflicts')
    op.drop_table('sync_conflicts')
    op.drop_index(op.f('ix_settlement_lines_settlement_id'), table_name='settlement_lines')
    op.drop_table('settlement_lines')
    op.drop_index(op.f('ix_slot_blocks_provider_id'), table_name='slot_blocks')
    op.drop_index('ix_slot_blocks_pitch_start', table_name='slot_blocks')
    op.drop_table('slot_blocks')
    op.drop_index(op.f('ix_channel_feeds_provider_id'), table_name='channel_feeds')
    op.drop_table('channel_feeds')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_due', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_provider_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_provider_webhooks_provider_id'), table_name='provider_webhooks')
    op.drop_table('provider_webhooks')
    op.drop_index(op.f('ix_provider_members_user_id'), table_name='provider_members')
    op.drop_index(op.f('ix_provider_members_provider_id'), table_name='provider_members')
    op.drop_table('provider_members')
    op.drop_index(op.f('ix_provider_api_keys_provider_id'), table_name='provider_api_keys')
    op.drop_index(op.f('ix_provider_api_keys_prefix'), table_name='provider_api_keys')
    op.drop_table('provider_api_keys')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_providers_status'), table_name='providers')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_table('providers')
    op.drop_table('broadcasts')
    op.drop_table('app_settings')
    op.drop_table('sports_catalog')
    op.drop_index('ix_auth_sessions_subject', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
