"""mirror tasks (manual other-app sync to-do)

Revision ID: 612f39a68710
Revises: 5b7e1d2a9c40
Create Date: 2026-09-12 16:46:23.819013+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '612f39a68710'
down_revision: str | None = '5b7e1d2a9c40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mirror_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('turf_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('lobby_id', sa.UUID(), nullable=False),
    sa.Column('booking_code', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('fk_mirror_tasks_lobby_id_lobbies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('fk_mirror_tasks_pitch_id_pitches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_mirror_tasks_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_mirror_tasks_resolved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_mirror_tasks_slot_id_slots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turf_id'], ['turfs.id'], name=op.f('fk_mirror_tasks_turf_id_turfs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mirror_tasks')),
    sa.UniqueConstraint('lobby_id', 'slot_id', 'action', name='uq_mirror_tasks_lobby_slot_action')
    )
    op.create_index('ix_mirror_tasks_provider_status', 'mirror_tasks', ['provider_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mirror_tasks_provider_status', table_name='mirror_tasks')
    op.drop_table('mirror_tasks')
    # ### end Alembic commands ###
